repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.0.0-alpha.4" # Use the sha / tag you want to point at
      hooks:
          - id: prettier
            types_or:
                - css
                - javascript
                - html
            entry: prettier --write --tab-width 4 --single-attribute-per-line true --embedded-language-formatting auto --trailing-comma es5 --ignore-unknown
